name: CI

on: [push, pull_request]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -e ".[dev]"

      # Ruff — non-blocking for now
      - run: ruff check . --exit-zero
      - run: ruff format --check --exit-zero

      # Type check (optional pass)
      - run: mypy fcot_re || true

      # Tests
      - run: pytest -q
